import type { StylePreset } from './types'

export const presets: StylePreset[] = [
  {
    id: 'chatgpt-dark',
    label: 'ChatGPT 深色',
    bgColor: '#212121',
    userBubbleBg: '#2f2f2f',
    aiBubbleBg: '#212121',
    textColor: '#ececec',
    userBubbleTextColor: '#ececec',
    aiTextColor: '#d1d5db',
    fontFamily: '"PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
    fontSize: 18,
    thinkingText: '正在思考...',
    modelName: 'FakeGPT-4o',
    logoUrl: '/logos/chatgpt.png',
    userAvatarColor: '#6366f1',
    aiAvatarColor: '#10a37f',
    bubbleRadius: 12,
    layout: 'all-left',
  },
  {
    id: 'chatgpt-light',
    label: 'ChatGPT 浅色',
    bgColor: '#ffffff',
    userBubbleBg: '#f7f7f8',
    aiBubbleBg: '#ffffff',
    textColor: '#374151',
    userBubbleTextColor: '#374151',
    aiTextColor: '#374151',
    fontFamily: '"PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
    fontSize: 18,
    thinkingText: '正在思考...',
    modelName: 'FakeGPT-4o',
    logoUrl: '/logos/chatgpt.png',
    userAvatarColor: '#6366f1',
    aiAvatarColor: '#10a37f',
    bubbleRadius: 12,
    layout: 'all-left',
  },
  {
    id: 'deepseek',
    label: 'DeepSeek',
    bgColor: '#1a1a2e',
    userBubbleBg: '#16213e',
    aiBubbleBg: '#1a1a2e',
    textColor: '#e0e0e0',
    userBubbleTextColor: '#e0e0e0',
    aiTextColor: '#a5b4fc',
    fontFamily: '"PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
    fontSize: 18,
    thinkingText: '深度思考中...',
    modelName: 'DeepFake-R1',
    logoUrl: '/logos/deepseek.png',
    userAvatarColor: '#4f7cff',
    aiAvatarColor: '#4f7cff',
    bubbleRadius: 14,
    layout: 'lr',
  },
  {
    id: 'claude',
    label: 'Claude',
    bgColor: '#2b2a27',
    userBubbleBg: '#3c3b38',
    aiBubbleBg: '#2b2a27',
    textColor: '#e8e4d9',
    userBubbleTextColor: '#e8e4d9',
    aiTextColor: '#d4a574',
    fontFamily: '"PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
    fontSize: 18,
    thinkingText: '思索中...',
    modelName: 'Fraud Opus',
    logoUrl: '/logos/claude.png',
    userAvatarColor: '#d97706',
    aiAvatarColor: '#d97706',
    bubbleRadius: 16,
    layout: 'lr',
  },
  {
    id: 'gemini',
    label: 'Gemini',
    bgColor: '#1e1e2e',
    userBubbleBg: '#313244',
    aiBubbleBg: '#1e1e2e',
    textColor: '#cdd6f4',
    userBubbleTextColor: '#cdd6f4',
    aiTextColor: '#89b4fa',
    fontFamily: '"PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
    fontSize: 18,
    thinkingText: '正在生成...',
    modelName: 'FakeGemini 2.5',
    logoUrl: '/logos/gemini.png',
    userAvatarColor: '#4285f4',
    aiAvatarColor: '#4285f4',
    bubbleRadius: 14,
    layout: 'lr',
  },
]
